## Numpy
So we are here with Numpy, our first library to learn, which is the fundamental package for scientific computing with Python.<br>
Let's start!<br><br>
<b>Note</b>: Some of the topics here are followed by some simple problems with instuctions, examples, sample outputs and expected outputs for you to practice along, so that you get clear with the concepts then and there! And also if it's not given, make sure you understand it well and you can also create new cells and practice on your own to clear your doubts!

1.Import the Numpy library using the syntax given below:<br>
**import numpy as np**

In [0]:
#Enter the syntax below and run the cell
import numpy as np


###### Creating an ndarray(n-dimensional array) from a list
The most important object defined in NumPy is an **N-dimensional array** type called **ndarray**. It describes the **collection of items of the same type**. Items in the collection can be accessed using a **zero-based index**(implies, the index of elements begins with 0 and not 1).<br><br>
We use the **array()** function of NumPy here.<br>
Note that, to access numpy's functions, we will use **np.function_name** syntax, where np is, you can say a shortform we use instead of writing numpy everytime.<br>
2.Create a **1D array** using the syntax given below:<br>
**array_name = np.array([list_elements])**

In [0]:
#Enter your code below
names = np.array(["Thushar", "Praroop", "Rakhil"])
#Example: a = np.array([5,10,15])

In [3]:
#You can print your 1D array here below:
print(names)
#Example: print(a) or just type a and run the cell
#Sample Output: ([5,10,15])

['Thushar' 'Praroop' 'Rakhil']


###### Creating an ndarray from a list of lists(Multidimensional arrays)
Same **array()** function is to be used here.<br><br>
3.Create a **2D array** using the syntax given below:<br>
**array_name = np.array([[elements_of_first_row], [elements_of_second_row], [...], ...])**

In [0]:
#Enter your code below
tronix = np.array([["Thushar", "Praroop", "Rakhil"], ["Stephy", "Tania", "Merlin"]])
#Example: b = np.array([[1,2,3],[2,4,6],[3,6,9]])

In [8]:
#You can print your 2D array here below:
print(tronix)
#Example: print(b) or just type b and run the cell
#Sample Output: ([[1,2,3],[2,4,6],[3,6,9]])

[['Thushar' 'Praroop' 'Rakhil']
 ['Stephy' 'Tania' 'Merlin']]


<b>Note:</b> I will be using these arrys, i.e, <b>a</b> and <b>b</b> in the following examples

###### Dimensions of the array
We use the **shape** attribute of array here.<br>
It returns a tuple with 2 elements,where first element equals to number of rows in the array and the second element equals to number of columns in the array.<br><br>
3.Print dimensions of your array using the syntax below:<br>
**array_name.shape**

In [11]:
#Enter your code below

#Example1: a.shape
#Sample Output1:(3,)
names.shape
#Example2: b.shape
#Sample Output2:(3,3)
tronix.shape

(2, 3)

###### arange(start,stop,step)
Like range function in python, the arange() function of Numpy gives us an array of evenly spaced elements within the interval [start,stop)(i.e, interval including start and excluding stop), instead of a list.<br>
'Step' is the spacing or difference between adjacent values.<br><br>
4.Create an array of **first 5 positive numbers divisible by 4** using the syntax given below:<br>
**array_name = np.arange(start,stop,step)**

In [0]:
#Enter your code below
five = np.arange(4,21,4)

In [19]:
#Print your array here below
print (list(five))
#Expected Output: ([4,8,12,16,20])

[4, 8, 12, 16, 20]


##### reshape(new_row_size,new_column_size)
The reshape() function is used to give a new shape to an array without changing its data.<br><br>
5.Reshape the below array, 'data' into an array with row size = <b>6</b> and column size = <b>2</b> using the syntax given below:<br>
**array_name.reshape(new_row_size,new_column_size)**

In [20]:
#Run this cell

data = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('My ndarray is \n',data)
print("\n Its size is:",data.shape)

My ndarray is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Its size is: (3, 4)


In [21]:
#Enter your code here below
data.reshape(6,2)
#Expected Output:([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

<b>Note</b>: (old_row_size * old_column_size) = (new_row_size * new_column_size)<br>
i.e, number of elements should not change while reshaping.

#### arange(start,stop,step).reshape(row_size,column_size)
Now we will use the **arange()**  and the **reshape()** functions together to create some ordered ndarray of required size as shown below using an example.<br>
So, look at the code below:

In [26]:
#Run this cell

c = np.arange(200).reshape(20,10)
print(list(c))

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29]), array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39]), array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49]), array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]), array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69]), array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79]), array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89]), array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99]), array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109]), array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119]), array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129]), array([130, 131, 132, 133, 134, 135, 136, 137, 138, 139]), array([140, 141, 142, 143, 144, 145, 146, 147, 148, 149]), array([150, 151, 152, 153, 154, 155, 156, 157, 158, 159]), array([160, 161, 162, 163, 164, 165, 166, 167, 168, 169]), array([170, 171, 172, 173, 174, 175, 176, 177, 178, 179]), array([180, 181, 182, 183, 184, 185, 186, 187, 

So, here we have a (5 * 6) ndarray with elements ranging from 0 to 29.Now you can practice on your own, but make sure that the **number of elements generated by the arange function should be equal to (row_size * column_size) given in the reshape function.**

Now, go through these functions and attributes with their syntax and explanation on your own and practice in the following cells, which include sufficient examples;<br>
<ul>
    <li><b>len(array_name)</b> - Gives length of array</li>
    <li><b>array_name.ndim</b> - Gives array dimensions</li>
    <li><b>array_name.size</b> - Gives the size of array(Total elements)</li>
    <li><b>array_name.dtype</b>- Gives the datatype of the elements</li>
    <li><b>type(array_name)</b>- Gives type of array</li>
</ul>

In [31]:
#Enter your code here
len(c)


#Example: len(b)
#Sample Output: 3

numpy.ndarray

In [32]:
#Enter you code here
c.ndim
#Example: b.ndim
#Sample Output: 2 

2

In [33]:
#Enter your code here
c.size
#Example: b.size
#Sample Output: 9

200

In [34]:
#Enter your code here
c.dtype

#Example: b.dtype
#Sample Output: int32

dtype('int64')

In [35]:
#Enter your code here
type(c)

#Example: type(b)
#Sample Output: numpy.ndarray

numpy.ndarray

#### Placeholders
In computer programming, a placeholder is a character, word, or string of characters that temporarily takes the place of the final data. Say, a programmer may know that he/she needs a certain number of values or variables, but doesn't yet know what to input. So one can use a placeholder in this case as a temporary solution until a proper value or variable can be assigned.<br>
Example: I want an array with three elements but their values get updated only later along the course, so i set a placeholder for it as<br>
***three_element_array = [0,0,0]***<br><br>
Now try out these different placeholders in Numpy along with the examples followed:<br>
<ul>
    <li><b>np.linspace(start, stop, length)</b> - Add evenly spaced values btw interval[start,stop] to  an array of length</li>
    <li><b>np.zeros((row_size, cloumn_size))</b> - Creates an array filled with zeros</li>
    <li><b>np.ones((row_size, column_size))</b> - Creates an array filled with ones</li>
    <li><b>np.random.random((row_size, column_size))</b> - Creates a random array</li>
    <li><b>np.empty((row_size, column_size))</b> - Creates an empty array</li>
    <li><b>np.full((row_size, column_size),fill_value,dtype)</b> - Creates a new array of given shape and type, filled with fill_value.</li>
</ul>

In [41]:
#Enter your code here
np.linspace(10,100,10)
#Example: np.linspace(0,10,6)
#Sample Output: ([ 0.,  2.,  4.,  6.,  8., 10.])

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [42]:
#Enter your code here
np.zeros((3,3))
#Example: np.zeros((1,2))
#Sample Output: ([[0.,0.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
#Enter your code here
np.ones((3,3))
#Example: np.ones((1,3))
#Sample Output:([[1.,1.,1.]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
#Enter your code here
np.random.random((3,3))
#Example: np.random.random((1,2))
#Sample Output: ([[0.55824656, 0.39591466]])

array([[0.19217338, 0.0107253 , 0.52992659],
       [0.49086071, 0.75388999, 0.68813269],
       [0.80961256, 0.37493524, 0.86508216]])

In [45]:
#Enter your code here
np.empty((3,3)) #Still generates arbitrary values
#Example: np.empty((1,2))
#Sample Output: ([[0.55824656, 0.39591466]])

array([[0.19217338, 0.0107253 , 0.52992659],
       [0.49086071, 0.75388999, 0.68813269],
       [0.80961256, 0.37493524, 0.86508216]])

Note - **np.empty(())** returns uninitialized(arbitrary) data of the given shape

#### Horizontal and vertical stacking
We will now combine two arrays vertically and horizontally.<br>
<ul><li><b>np.hstack((first_array,second_array))</b> - Combine/Stack array column wise</li>
    <li><b>np.vstack((first_array,second_array))</b> - Combine/Stack array row-wise</li></ul>
Follow the steps with instructions along with examples and come on let's <b>practice</b>:

**Note**:<ul>
    <li>For vertical stacking, number of columns should be same.</li>
<li>And for horizontal stacking, number of rows should be same.</li></ul>

In [54]:
#First create two arrays
#Enter your code below
x = np.arange(1,6)
y = np.arange(1,10,2)
print(y)
print(x)
#Example: x=np.arange(1,5) and y=np.arange(2,9,2)
#x=([1,2,3,4]) and y=([2,4,6,8])

[1 3 5 7 9]
[1 2 3 4 5]


In [55]:
#Vertical stacking
#Enter your code below
v = np.vstack((x,y))
#Example: v = np.vstack((x,y))
#Print v
print(v)
#Sample Output: ([[1, 2, 3, 4],[2, 4, 6, 8]])

[[1 2 3 4 5]
 [1 3 5 7 9]]


In [57]:
#Horizontal stacking
#Enter your code below
h = np.hstack((x,y))
#Example: h = np.hstack((x,y))
#Print h
print(h)
#Sample Output: ([1, 2, 3, 4, 2, 4, 6, 8])

[1 2 3 4 5 1 3 5 7 9]


To get a better understanding of what actually happens when we use these functions, have a look at the pictorial representions of [horizontal stacking](https://www.w3resource.com/numpy/manipulation/hstack.php) and [vertical stacking](https://www.w3resource.com/numpy/manipulation/vstack.php).

#### Horizontal and vertical splitting
Now, we can split the arrays we combined using the functions given below.
<ul>
    <li><b>np.hsplit(array,indices_or_sections)</b> - used to split an array into multiple sub-arrays horizontally (column-wise)</li>
    <li><b>np.vsplit(array,indices_or_sections)</b> - used to split an array into multiple sub-arrays vertically (row-wise)</li>
</ul>
We use the stacked arrays <b>h</b> and <b>v</b> here again in the examples,<br>
where, <b>v = ([[1, 2, 3, 4],[2, 4, 6, 8]])</b> and <b>h = ([1, 2, 3, 4, 2, 4, 6, 8])</b><br>
You can also do the same with your examples or create new ndarrays if u want.

In [58]:
#Vertical splitting
#Enter your code here
np.vsplit(v,2)
#Example: np.vsplit(v,2)
#Sample Output: [array([[1, 2, 3, 4]]), array([[2, 4, 6, 8]])]

[array([[1, 2, 3, 4, 5]]), array([[1, 3, 5, 7, 9]])]

In [59]:
#Horizontal splitting
#Enter your code here
np.hsplit(h,2)
#Example: np.hsplit(h,2)
#Sample Output: [array([1, 2, 3, 4]), array([2, 4, 6, 8])]

[array([1, 2, 3, 4, 5]), array([1, 3, 5, 7, 9])]

Visit this link to visualise [vertical splitting](https://www.w3resource.com/numpy/manipulation/vsplit.php).<br>
And visit this link to visualize [horizontal splitting](https://www.w3resource.com/numpy/manipulation/hsplit.php).

#### Floor and Ceil
<ul>
    <li><b>np.floor(array)</b> - returns floor of elements of array</li>
    <li><b>np.ceil(array)</b> - returns ceil of elements of array</li>
</ul>
Example: a = 5.6<br>
floor(a) = 5<br>
ceil(a) = 6

In [60]:
#Run this cell
#Creating a random array
c = np.random.random((2,3))
print(c)

[[0.11778396 0.6990992  0.74878452]
 [0.75411978 0.08947613 0.71395816]]


In [63]:
#floor
#Enter your code below
np.floor(c)
#Example: np.floor(c)
#Sample Output: ([[0., 0., 0.],[0., 0., 0.]])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
#ceil
#Enter your code below
np.ceil(c)
#Example: np.ceil(c)
#Sample Output:([[1., 1., 1.],[1., 1., 1.]])

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Squeeze and Expand
<ul>
<li><b>np.squeeze(array,axis)</b> - used to remove single-dimensional entries from the shape of an array.</li>
<li><b>np.expand_dims(array,axis)</b> - expands the shape of an array i.e, inserts a new axis that will appear at the axis position in the expanded array shape.</li>
</ul>
Let's see the example below:

In [65]:
#Run this cell
#Suppose we have a three dimensional ndarray as given below
three_dim = np.array([[[10],[20],[30]]])
print('three_dim = ',three_dim)
print('Shape = ',three_dim.shape)

three_dim =  [[[10]
  [20]
  [30]]]
Shape =  (1, 3, 1)


As you see above **three_dim** is a three dimensional array with shape **(1,3,1)**, now suppose I want to access this ndarray I will need to specify three indices, which is just an unnecessary task in this case.So it's better to squeeze the unwanted dimensions or the single dimensions here and access the elements easily.
<br>Let's see how we will squeeze this ndarray below:

In [66]:
#Run this cell
one_dim = np.squeeze(three_dim)
print('Squeezed array = ',one_dim)
print('Shape = ',one_dim.shape)

Squeezed array =  [10 20 30]
Shape =  (3,)


And now you can easily manipulate this squeezed array for your desired operations.<br><br>
Now, what if we have a case that is opposite to it in hand, i.e, suppose I have a two dimensional array and I want to perform an operation to it with a three dimensional array operand, so here we will need to expand the dimensions of our 2D array and let's see how we do it with **np.expand_dims()**:

In [67]:
#Run this cell
two_dim = np.array([[10],[20],[30]])
print('two_dim = ',two_dim)
print('Shape = ',two_dim.shape)

two_dim =  [[10]
 [20]
 [30]]
Shape =  (3, 1)


Now, let's expand this to a 3D array to make the dimensions of the operands equal, so that we could perform the operation with a 3D operand easily. 

In [69]:
#Run this cell
dim_three = np.expand_dims(two_dim,axis=0)
print('dim_three = ',dim_three)
print('Shape = ',dim_three.shape)

dim_three =  [[[10]
  [20]
  [30]]]
Shape =  (1, 3, 1)


So now we got a 3D array with dimensions **(1 * 3 * 1 )**.Here I expanded it along the horizontal axis, i.e, **axis=0** to get a three dimensional array of the dimensions (1 * 3 * 1). Had it been, along the vertical axis,i.e, **axis=1**, I would have got a 3D array of dimensions **(3 * 1 * 1)**.<br>
Remember this is just a random example where I am not specific about the exact number of elements in each dimension to perform the operation.In practical situations, we have to manipulate ndarrays using these functions in accordance to our requirement!So I suggest to practice on your own to get a better idea of this topic.<br>
And also refer these links to visualise [squeeze](https://www.w3resource.com/numpy/manipulation/squeeze.php) and [expand_dims](https://www.w3resource.com/numpy/manipulation/expand-dims.php) operations.

#### Transpose and dot product of matices
<ul>
    <li><b>array.T</b> - It gives the transpose of a matrix</li>
    <li><b>np.dot(arra1,array2)</b> - Returns dot product of two arrays</li>
</ul>
Understand with examples and learn with practice!

In [70]:
#Enter your code here
v.T
#Example: v.T
#v = ([[1, 2, 3, 4],[2, 4, 6, 8]])
#Sample Output: ([[1, 2],[2, 4],[3, 6],[4, 8]])

array([[1, 1],
       [2, 3],
       [3, 5],
       [4, 7],
       [5, 9]])

In [71]:
#Run this cell
p = np.arange(0,6).reshape(2,3)
q = np.arange(0,6).reshape(3,2)
print('p=',p)
print('q=',q)

p= [[0 1 2]
 [3 4 5]]
q= [[0 1]
 [2 3]
 [4 5]]


In [74]:
#Enter your code here
t =np.dot(p,q)
#Example:t = np.dot(p,q)
#Print t
print (t)
#Sample Output: ([[10, 13],[28, 40]])

[[10 13]
 [28 40]]


##### Sum()
<ul>
    <li><b>array.sum()</b> - Sum of all the elements</li>
    <li><b>array.sum(axis=0)</b> - Column sum</li>
    <li><b>array.sum(axis=1)</b> - Row sum</li>
</ul>where array is an ndarray.<br><br>
Take a look at the examples below where we use <b>t</b> from the above example and <b>t = ([[10, 13],[28, 40]])</b>.<br>
Give it a try on your own with the ndarrays that you have used before or you can always create your own.

In [75]:
#Enter your code here
t.sum()
#Example: t.sum()
#Sample Output: 91

91

In [76]:
#Enter your code here
t.sum(axis=0)
#Example: t.sum(axis=0)
#Sample Output: ([38, 53])

array([38, 53])

In [77]:
#Enter your code here
t.sum(axis=1)
#Example: t.sum(axis=1)
#Sample Output: ([23, 68])

array([23, 68])

Similarly,try out these functions too and do not forget to practice okay?<br>
<ul>
    <li><b>ndarray.min()</b> - to calculate the minimum value</li>
    <li><b>ndarray.max()</b> -  to calculate the maximum value</li>
    <li><b>ndarray.mean()</b> - to calculate the mean average value</li>
</ul>

In [79]:
t.mean()

22.75

#### Cumsum()
<ul>
    <li><b>array.cumsum()</b> - (Default case) Returns the cumilative sum over the flattened array.</li>
    <li><b>array.cumsum(axis=0)</b> - Returns cumilative sum of the elements along the columns.</li>
    <li><b>array.cumsum(axis=1)</b> - Returns cumilative sum of the elements along the rows.</li>
</ul>where array is an ndarray.<br><br>
Are you wondering what a flattened array is?Let's see some examples to clear your doubts and don't forget to try it on your own!<br>

In [80]:
#Enter your code here
t.cumsum()
#Example: t.cumsum() (where t is an ndarray and t = [[10, 13],[28, 40]] as used in the examples before. )
#Output: [10, 23, 51, 91]
#You can see that the 2D array is flattened into one and the cumilative sums are calculated along the single row of the list

array([10, 23, 51, 91])

In [81]:
#Enter your code here
t.cumsum(axis=0)
#Example: t.cumsum(axis=0)
#Output: [[10, 13],[38, 53]]
#Here note that the cumilative sum is computed along the columns in the 2D array

array([[10, 13],
       [38, 53]])

In [82]:
#Enter your code here
t.cumsum(axis=1)
#Example: t.cumsum(axis=1)
#Output:[[10, 23],[28, 68]]
#Here note that the cumilative sum is computed along the rows in the 2D array

array([[10, 23],
       [28, 68]])

#### Remember
**axis=0** specifies column or vertical axis.<br>
**axis=1** specifies row or horizontal axis<br>

##### Note!!
You will be probably thinking that, when we have lists in python then why use NumPy's ndarray data structure, right?<br>
We will take the last function we practiced now as an example,i.e, the sum( ) function. Now, if we wanted to calculate the column sum of each column or row sum of each row for a list of lists(2D lists), we would require a for loop to access each list to calulate it's sum and it won't be efficient at all when we have a large number of lists.<br>
<br>
And that's why we use the NumPy library.Using NumPy library, we can replace for loops with operations applied to multiple data points at once.This is called **vectorization** and ndarrays make vectorization possible!<br>
These vectorized operations help take a lot of the mental load out of working with big collections of values when you basically want to do the same thing to all of them, treating the logic like you’re just working with one number. You don’t write any loops of your own!<br><br>
**The NumPy library takes advantage of a processor feature called <i>Single Instruction Multiple Data (SIMD)</i> to process data faster. SIMD allows a processor to perform the same operation, on multiple data points, in a single processor cycle.**

### Vectorisation in ndarrays
Let's see the example below to get a better understanding of the concept.

In [84]:
#Run this cell
x = np.array([1,2,3,4])
y = np.array([4,3,2,1])
z = x + y
print(z)

[5 5 5 5]


We have now **"vectorized"** the addition operation, making it work for vectors. The NumPy library has a whole bunch of vectorized functions, including square root, absolute value, trigonometry functions, logarithmic functions, exponential functions, and more.<br>
Now try out **vectorizing multiplication, subtraction and exponential operations** on your own.

In [86]:
#Vectorize multiplication operation
w = x * y
print(w)

[4 6 6 4]


In [87]:
#Vectorize subtraction operation
sub = x-y
print(sub)

[-3 -1  1  3]


In [88]:
#Vectorize exponential operation
exp = x ** y
print(exp)

[1 8 9 4]


### Broadcasting  in ndarrays
OK, so far we’ve figured out that the idea behind **vectorization** is to make operations between two collections of the **same size and shape** as intuitive as operations between two single numbers. <br>
But what about when the collections are **different shapes**? <br>
This is when we apply a concept known as **broadcasting**. Broadcasting is the act of extending an array to a shape that will allow it to successfully take part in a vectorized calculation. <br>
Let's again go with an example to figure out this concept in a better manner

In [89]:
#Run this cell
l = np.array([1,2,3,4])
m = 10
n = l*m
print(n)

[10 20 30 40]


So, didn't you notice how 10 was multiplied to all the numbers in the list, l. Here the single element 10 in m is **broadcasted** to [10,10,10,10] to perform the given operation.This feature of python is called broadcasting!<br>
So now you can **practice** this on your own with **any operation** you like.

In [0]:
#Practice here


Rules of broadcasting are given below:<br>
<ul>
<li>If the two arrays are of the same length in a dimension, that dimension will be operated on in an element-wise manner. </li>
<li>If one array has some number in a dimension and the other array is only size 1 in that dimension, that value will be broadcasted, and it will be used with each item in the other array. </li>
<li>If the two arrays are different sizes and neither is size 1, broadcasting can't be performed, and an error is thrown.</li>
</ul>

#### Activity
So here is a very small activity for you to do:<br>
Try out following functions that you might have used with lists in python:
    <ul>
    <li>array.flatten()</li>
    <li>np.append(array,element)</li>
    <li>np.delete(array,element,axis)</li>
    <li>np.copy(array)</li>
    <li>insert(array,element1,element2,...axis)</li>
    <li>array.sort(axis)</li><br>
    </ul>
You can also explore other functions on your own!<br>
The link to complete reference guide for Numpy is given below to enhance your knowledge on the same:<br>
[Reference guide](https://numpy.org/doc/1.18/numpy-ref.pdf)
<br>
And a more simplified explanation can be found here.[Simplified overview](https://www.w3resource.com/numpy/manipulation/index.php)
<br>
[Detailed info on Numpy](https://likegeeks.com/numpy-array-tutorial/)
#### Happy learning!

In [121]:
import numpy as np
h1 = np.arange(1,6).shape(2,3)
 
print(h1)


TypeError: ignored